export const EVENT_TYPES = [
  'Torneo',
  'Liga',
  'Final de liga',
  'Drafteo',
  'Sellado',
  'Pre-release',
  'Presentación',
  'Lanzamiento',
  'Demostración',
  'Quedada',
  'Casual / Juego libre',
  'Evento de iniciación',
  'Tarde temática',
  'Evento cooperativo',
  'Campaña narrativa',
  'Charla / Taller',
  'Pintado de miniaturas',
  'Interclubes',
  'Campeonato',
  'Evento familiar / Infantil',
  'Evento benéfico / Solidario',
  'Mercadillo / Intercambio',
  'Escape room / Enigma',
  'Otro'
];